### PR TITLE
Add config

### PR DESCRIPTION
**Pull request by alternateved**
Enable users to change their dmenu command in order to theme it or change other variables like wallpaper directory.

### CODE REVIEW

**Comment by HeavyRain266** [comment]
Thanks! 
Could you rebase all commits in those pull requests before merge?

**Comment by alternateved** [comment]
Hmm, happily, but I am not sure how I am suppose to do this.

**Comment by HeavyRain266** [comment]
> Hmm, happily, but I am not sure how I am supposed to do this.

use `git rebase -i HEAD~<number of commits>` then select which commit to squash and add `--force` to push command

**Comment by alternateved** [comment]
Ah, sorry. It seems I lack experience with git and you lost me there.

**Comment by HeavyRain266** [comment]
No worries, I will rebase it someday manually also forgot to mention upcomming changes in readme, I'm thinking about switching from bash to compiled language or something to bundle distribute it as small binary with flags

**Comment by HeavyRain266** [comment]
I don't have bash installed and mksh linked as default shell and there is bash because of some users reporting problems on discord because like some distros tends to link dash or other shells in place of posix shell "sh" and added bash for better compatibility on Debian based distros which are using dash linked as sh.

**Comment by alternateved** [comment]
Ah, I see. I am using zsh on NixOS myself. I couldn't use the scripts unless I performed the first change or just run them with bash command. Do you have any idea which compiled language would that be for the future relases?

**Comment by HeavyRain266** [comment]
> Do you have any idea which compiled language would that be for the future relases? 

Most likely Go or Rust, I will bind bemenu headers use it as lib, user will be able to choose between ncurses menu or graphical one + will add config file, more layouts and dynamic values for frames to allow people easly change size of frames because actually those layouts are made for 1920x1080 screen, I will open discussion post tomorrow for this.

**Pull request merged**
